//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PostTrainingFrontend.CartWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CartWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CartWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddToCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCartByUserIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCartItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReduceItemAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncreaseItemAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveFromCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearCartOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CartWebService() {
            this.Url = global::PostTrainingFrontend.Properties.Settings.Default.PostTrainingFrontend_CartWebService_CartWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddToCartCompletedEventHandler AddToCartCompleted;
        
        /// <remarks/>
        public event GetCartByUserIdCompletedEventHandler GetCartByUserIdCompleted;
        
        /// <remarks/>
        public event GetCartItemCompletedEventHandler GetCartItemCompleted;
        
        /// <remarks/>
        public event ReduceItemAmountCompletedEventHandler ReduceItemAmountCompleted;
        
        /// <remarks/>
        public event IncreaseItemAmountCompletedEventHandler IncreaseItemAmountCompleted;
        
        /// <remarks/>
        public event RemoveFromCartCompletedEventHandler RemoveFromCartCompleted;
        
        /// <remarks/>
        public event ClearCartCompletedEventHandler ClearCartCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddToCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddToCart(string userId, string productId, int quantity) {
            object[] results = this.Invoke("AddToCart", new object[] {
                        userId,
                        productId,
                        quantity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddToCartAsync(string userId, string productId, int quantity) {
            this.AddToCartAsync(userId, productId, quantity, null);
        }
        
        /// <remarks/>
        public void AddToCartAsync(string userId, string productId, int quantity, object userState) {
            if ((this.AddToCartOperationCompleted == null)) {
                this.AddToCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddToCartOperationCompleted);
            }
            this.InvokeAsync("AddToCart", new object[] {
                        userId,
                        productId,
                        quantity}, this.AddToCartOperationCompleted, userState);
        }
        
        private void OnAddToCartOperationCompleted(object arg) {
            if ((this.AddToCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddToCartCompleted(this, new AddToCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCartByUserId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCartByUserId(string userId) {
            object[] results = this.Invoke("GetCartByUserId", new object[] {
                        userId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCartByUserIdAsync(string userId) {
            this.GetCartByUserIdAsync(userId, null);
        }
        
        /// <remarks/>
        public void GetCartByUserIdAsync(string userId, object userState) {
            if ((this.GetCartByUserIdOperationCompleted == null)) {
                this.GetCartByUserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCartByUserIdOperationCompleted);
            }
            this.InvokeAsync("GetCartByUserId", new object[] {
                        userId}, this.GetCartByUserIdOperationCompleted, userState);
        }
        
        private void OnGetCartByUserIdOperationCompleted(object arg) {
            if ((this.GetCartByUserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCartByUserIdCompleted(this, new GetCartByUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCartItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCartItem(string userId, string productId) {
            object[] results = this.Invoke("GetCartItem", new object[] {
                        userId,
                        productId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCartItemAsync(string userId, string productId) {
            this.GetCartItemAsync(userId, productId, null);
        }
        
        /// <remarks/>
        public void GetCartItemAsync(string userId, string productId, object userState) {
            if ((this.GetCartItemOperationCompleted == null)) {
                this.GetCartItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCartItemOperationCompleted);
            }
            this.InvokeAsync("GetCartItem", new object[] {
                        userId,
                        productId}, this.GetCartItemOperationCompleted, userState);
        }
        
        private void OnGetCartItemOperationCompleted(object arg) {
            if ((this.GetCartItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCartItemCompleted(this, new GetCartItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReduceItemAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReduceItemAmount(string userId, string productId) {
            object[] results = this.Invoke("ReduceItemAmount", new object[] {
                        userId,
                        productId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReduceItemAmountAsync(string userId, string productId) {
            this.ReduceItemAmountAsync(userId, productId, null);
        }
        
        /// <remarks/>
        public void ReduceItemAmountAsync(string userId, string productId, object userState) {
            if ((this.ReduceItemAmountOperationCompleted == null)) {
                this.ReduceItemAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReduceItemAmountOperationCompleted);
            }
            this.InvokeAsync("ReduceItemAmount", new object[] {
                        userId,
                        productId}, this.ReduceItemAmountOperationCompleted, userState);
        }
        
        private void OnReduceItemAmountOperationCompleted(object arg) {
            if ((this.ReduceItemAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReduceItemAmountCompleted(this, new ReduceItemAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncreaseItemAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IncreaseItemAmount(string userId, string productId) {
            object[] results = this.Invoke("IncreaseItemAmount", new object[] {
                        userId,
                        productId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IncreaseItemAmountAsync(string userId, string productId) {
            this.IncreaseItemAmountAsync(userId, productId, null);
        }
        
        /// <remarks/>
        public void IncreaseItemAmountAsync(string userId, string productId, object userState) {
            if ((this.IncreaseItemAmountOperationCompleted == null)) {
                this.IncreaseItemAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncreaseItemAmountOperationCompleted);
            }
            this.InvokeAsync("IncreaseItemAmount", new object[] {
                        userId,
                        productId}, this.IncreaseItemAmountOperationCompleted, userState);
        }
        
        private void OnIncreaseItemAmountOperationCompleted(object arg) {
            if ((this.IncreaseItemAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncreaseItemAmountCompleted(this, new IncreaseItemAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveFromCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RemoveFromCart(string userId, string productId) {
            object[] results = this.Invoke("RemoveFromCart", new object[] {
                        userId,
                        productId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveFromCartAsync(string userId, string productId) {
            this.RemoveFromCartAsync(userId, productId, null);
        }
        
        /// <remarks/>
        public void RemoveFromCartAsync(string userId, string productId, object userState) {
            if ((this.RemoveFromCartOperationCompleted == null)) {
                this.RemoveFromCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveFromCartOperationCompleted);
            }
            this.InvokeAsync("RemoveFromCart", new object[] {
                        userId,
                        productId}, this.RemoveFromCartOperationCompleted, userState);
        }
        
        private void OnRemoveFromCartOperationCompleted(object arg) {
            if ((this.RemoveFromCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveFromCartCompleted(this, new RemoveFromCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearCart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ClearCart(string userId) {
            object[] results = this.Invoke("ClearCart", new object[] {
                        userId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ClearCartAsync(string userId) {
            this.ClearCartAsync(userId, null);
        }
        
        /// <remarks/>
        public void ClearCartAsync(string userId, object userState) {
            if ((this.ClearCartOperationCompleted == null)) {
                this.ClearCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearCartOperationCompleted);
            }
            this.InvokeAsync("ClearCart", new object[] {
                        userId}, this.ClearCartOperationCompleted, userState);
        }
        
        private void OnClearCartOperationCompleted(object arg) {
            if ((this.ClearCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearCartCompleted(this, new ClearCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AddToCartCompletedEventHandler(object sender, AddToCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddToCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddToCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCartByUserIdCompletedEventHandler(object sender, GetCartByUserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCartByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCartByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetCartItemCompletedEventHandler(object sender, GetCartItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCartItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCartItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ReduceItemAmountCompletedEventHandler(object sender, ReduceItemAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReduceItemAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReduceItemAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IncreaseItemAmountCompletedEventHandler(object sender, IncreaseItemAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncreaseItemAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncreaseItemAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RemoveFromCartCompletedEventHandler(object sender, RemoveFromCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveFromCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveFromCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ClearCartCompletedEventHandler(object sender, ClearCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClearCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ClearCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591